/* Automatically generated by './build/bin/libs-entry.js' */

import Checkbox from '../packages/checkbox/index.js';
import Input from '../packages/input/index.js';
import Select from '../packages/select/index.js';

const components = [
  Checkbox,
Input,
Select
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.0',
  install,
  Checkbox,
Input,
Select
};
